### ISSUE TITLE
Random test failure - Client bidirectional Streaming

### ISSUE THREAD

**Issue by AdrianRaFo** [frees-io/freestyle-rpc#237] opened 2018-04-11 13:38 UTC
A random failure on the test :

"frees-rpc client should be able to run client bi-directional streaming services"

with the error:
```
List() was not equal to 
List(E(A(100,200),foo3), E(A(1000,2000),foo4))
```

is ignored on Travis for now

**Comment by fedefernandez** [comment] 2018-04-17 08:36
Possible duplicated by #164

**Comment by L-Lavigne** [comment] 2018-05-23 20:49
Closing as duplicate of #164 since those only seem to happen for FS2 bidi tests; let's (re-)open as a separate issue if we see it happening with Monix and/or non-bidi tests.

(Folks getting notifications for the testing issues: sorry to have gotten your hopes up)

**Closed by L-Lavigne** 2018-05-23 20:49 UTC
Labels: bug, duplicate, help wanted, tests
